pullPolicy: "IfNotPresent"
ingressClassName: "haproxy"
#tls:
#  - secretName: tls-example-com
#    hosts:
#      - one.example.com
#      - two.example.com

images:
  fhirviz:
    repository: "taktik/ehealth-fhirviz"
    tag: ""
    replicaCount: 1
    javaOpts: "-XX:MaxRAMPercentage=70"
    memoryRequest: "4Gi"
    cpuRequest: 5m
    cpuLimit: 2
    debug: true
    env: {}

paths:
  /: {}
