pullPolicy: "IfNotPresent"
ingressClassName: "haproxy"
#tls:
#  - secretName: tls-example-com
#    hosts:
#      - one.example.com
#      - two.example.com

images:
  fhirviz:
    repository: "icure/ehealth-fhirviz"
    tag: ""
    replicaCount: 1
    javaOpts: "-Xmx1024m"
    memoryRequest: "2Gi"
    cpuRequest: 5m
    cpuLimit: 2
    debug: true
    env: {}

paths:
  /: {}
